### PR TITLE
Call jest directly instead of 'tsdx test' // #1

### PR DESCRIPTION
**Pull request by lourot**
@killerkc12 is this what you had in mind? If not or if slightly different, feel free to create another PR and I'll abandon this one, thanks!

### CODE REVIEW

**Comment by killerkc12** [comment]
Yes, but only this change won't work.
Now it will find the jest.config.js file which doesn't exist right now.

I'm just curious to know, what is the reason you prefer to refer to the jest.config.json but not jest?

**Comment by lourot** [comment]
Actually we have a https://github.com/Frameright/react-image-display-control/blob/main/jest.config.json file, and the tests are working on this branch:

```
$ npm run test

> @frameright/react-image-display-control@1.0.5 test
> jest

 PASS  test/index.test.tsx
  it
    ✓ renders without crashing (11 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.069 s
Ran all test suites.
```

do you feel like something is missing?

**Comment by killerkc12** [comment]
I won't say anything about the jest.config.json file because I never used it yet.
I mainly used jest for most of the project and the config was handled by jest.config.js, using global tsconfigs for js-jest.

**Comment by lourot** [comment]
I'm not sure I understand, but what about this: I'd merge this PR and you could create another one in order to show me what you'd like to change. Does that work for you?

**Comment by killerkc12** [comment]
Yes sure. I will create the PR and will let you know

**Pull request merged**
