### PR TITLE
Remove tsdx from package.json #23

### PR DESCRIPTION
**Pull request by sakibian**
1. `npm start && npm run build` successfull.
npm start   npm run build

2. Jest Error on src/index.tsx
jest error
jest error in src-index
issue arise after package modify

If these issues are major for the project then you can go with alternative solutions:
1. https://www.libhunt.com/compare-tsdx-vs-parcel?ref=compare
2. https://www.libhunt.com/compare-tsdx-vs-microbundle?ref=compare
3. https://www.libhunt.com/compare-tsdx-vs-nx?ref=compare

TLDR: You can plan for alternative solutions at your convenience. Of course, you don't have to merge this PR with your own but you can test it though.

Thank you.

### CODE REVIEW

**Review by lourot — CHANGES_REQUESTED** [review]
Thanks a lot @sakibian! It seems like `tsc --build` doesn't do as much as `tsdx build`. `tsdx build` used to produce a `dist/` folder that would get published by `npm pack`.  `tsc --build` doesn't produce the `dist/` folder.

You can see that this goes wrong if you attempt to clean build the example:

```
cd example/
./clean-build-and-run.sh

[...]
+ mv ../frameright-react-image-display-control-1.0.5.tgz frameright-react-image-display-control.tgz
+ npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

added 232 packages, and audited 233 packages in 25s

91 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
+ npm run build

> build
> parcel build index.html

🚨 Build failed.

@parcel/core: Failed to resolve '@frameright/react-image-display-control' from './index.tsx'

  /home/lourot/Documents/git/frameright/react-image-display-control/example/index.tsx:4:37
    3 | import { createRoot } from 'react-dom/client';
  > 4 | import { ImageDisplayControl } from '@frameright/react-image-display-control';
  >   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    5 | 
    6 | const App = () => {

@parcel/resolver-default: Could not load './dist/react-image-display-control.esm.js' from module '@frameright/react-image-display-control' found in package.json#module

  /home/lourot/Documents/git/frameright/react-image-display-control/example/node_modules/@frameright/react-image-display-control/package.json:56:13
    55 |   },
  > 56 |   "module": "dist/react-image-display-control.esm.js",
  >    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ './dist/react-image-display-control.esm.js' does not exist'
    57 |   "devDependencies": {
    58 |     "@types/react": "^18.2.7",
```

This is because the `frameright-react-image-display-control.tgz` generated by `npm build && npm pack` now lacks the `dist/` folder.

We need to figure out what else `tsdx build` was doing. I think it is also, for example, calling `rollup`?

**Comment by sakibian** [comment]
If you mean to change library/framework I can test it out for you with alternatives.
Yes @AurelienLourot, it is indeed rollup.

**Comment by sakibian** [comment]
I see you have used parcel, Ok will look into deep for the solution.

**Comment by lourot** [comment]
Thank you, I see `npm run build` / `tsdx build` is really just calling `rollup`: https://github.com/jaredpalmer/tsdx/blob/master/src/index.ts#L408

And we should give it a try at directly calling rollup on our own and see if this works?

The `npm start` command we can remove, we don't use it.

Yes the example (`example/package.json`) uses parcel but I don't think `package.json` does

**Review by lourot — CHANGES_REQUESTED** [review]
Thanks a lot @sakibian! It seems like `eslint` is missing now, see the CI failure. It was probably a dependency of `tsdx` and now needs to be added explicitly to `package.json`. You can also validate locally by running `npm run lint`

**Comment by sakibian** [comment]
@AurelienLourot I think we are going somewhere now :), 

1. `parcel` added & `npm install` works without any issue.
parcel-works-npm-install

2. `npm start` works with no issue.
parcel-watch-starts-with-no-issue

3 `npm run build` works too.
parcel-npm-run-build-works

4. `dist` compiling is happening as we wanted.
dist-compiling-works

**Comment by sakibian** [comment]
`git commit -m "Lint, prettier, jest re-configured"`

> @frameright/react-image-display-control@1.0.5 lint
> eslint . --ignore-pattern dist && prettier --check .

Checking formatting...
All matched files use Prettier code style!

> @frameright/react-image-display-control@1.0.5 test
> jest

```
ts-jest[versions] (WARN) Module jest is not installed. If you're experiencing issues, consider installing a supported version (>=29.0.0 <30.0.0-0).
ts-jest[versions] (WARN) Version 5.1.6 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=4.3.0 <5.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
Jest encountered an unexpected token
```

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
 • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
 • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/configuration
For information about custom transformations, see:
https://jestjs.io/docs/code-transformation

Details:
```

C:\laragon\www\opensource\react-image-display-control\node_modules\@frameright\image-display-control-web-component\dist\src\image-display-control.js:2
import '@ungap/custom-elements';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at Runtime.createScriptFromCode (C:\Users\Sakib\AppData\Roaming\npm\node_modules\jest\node_modules\jest-runtime\build\index.js:1496:14)
    at Runtime._execModule (C:\Users\Sakib\AppData\Roaming\npm\node_modules\jest\node_modules\jest-runtime\build\index.js:1390:25)
    at Runtime._loadModule (C:\Users\Sakib\AppData\Roaming\npm\node_modules\jest\node_modules\jest-runtime\build\index.js:1013:12)
    at Runtime.requireModule (C:\Users\Sakib\AppData\Roaming\npm\node_modules\jest\node_modules\jest-runtime\build\index.js:873:12)
    at Runtime.requireModuleOrMock (C:\Users\Sakib\AppData\Roaming\npm\node_modules\jest\node_modules\jest-runtime\build\index.js:1039:21)
    at C:\laragon\www\opensource\react-image-display-control\src\index.tsx:25:3
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
husky - pre-commit hook exited with code 1 (error)
```

**Comment by sakibian** [comment]
`npm start`

> @frameright/react-image-display-control@1.0.5 start
> parcel watch

✨ Built in 273ms

**Comment by sakibian** [comment]
`npm run lint`

> @frameright/react-image-display-control@1.0.5 lint
> eslint . --ignore-pattern dist && prettier --check .

Checking formatting...
All matched files use Prettier code style!

**Comment by sakibian** [comment]
`npm run prepare`

> @frameright/react-image-display-control@1.0.5 prepare
> husky install && parcel build

husky - Git hooks installed
✨ Built in 774ms

```
dist\main.js                               19.58 KB    80ms
dist\types.d.ts                               247 B    64ms
dist\react-image-display-control.esm.js    19.19 KB    79ms
```

**Comment by sakibian** [comment]
`npm run build`

> @frameright/react-image-display-control@1.0.5 build
> parcel build

✨ Built in 563ms

```
dist\main.js                               19.58 KB    80ms
dist\types.d.ts                               247 B    64ms
dist\react-image-display-control.esm.js    19.19 KB    79ms
```

**Comment by sakibian** [comment]
git commit -m "Lint, prettier, jest re-configured"

> @frameright/react-image-display-control@1.0.5 lint
> eslint . --ignore-pattern dist && prettier --check .

Checking formatting...
All matched files use Prettier code style!

> @frameright/react-image-display-control@1.0.5 test
> jest

```
Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.033 s
Ran all test suites.
Error: ● Invalid transformer module:
  "C:/laragon/www/opensource/react-image-display-control/tsconfig.json" specified in the "transform" object of Jest configuration
  must export a `process` or `processAsync` or `createTransformer` function.
  Code Transformation Documentation:
  https://jestjs.io/docs/code-transformation

    at C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\transform\build\ScriptTransformer.js:339:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ScriptTransformer.loadTransformers (C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\transform\build\ScriptTransformer.js:317:5)
    at async createScriptTransformer (C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\transform\build\ScriptTransformer.js:998:3)
    at async C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\core\build\TestScheduler.js:221:33
    at async Promise.all (index 0)
    at async TestScheduler.scheduleTests (C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\core\build\TestScheduler.js:217:7)
    at async runJest (C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\core\build\runJest.js:367:19)
    at async _run10000 (C:\laragon\www\opensource\react-image-display-control\node_modules\@jest\core\build\cli\index.js:343:7)
husky - pre-commit hook exited with code 1 (error)
```

**Comment by sakibian** [comment]
1. In package.json 

```
`"@types/jest": "^29.0.0"`
`"jest": "^29.0.0"`
`"jest-environment-jsdom": "^29.0.0"`
`"ts-jest": "^29.0.0",`
```
All of them are the same version - saw the same issue in angular on StackOverflow, some say because of a version mismatch

2. On commit this issue arises:

```
`.....\tsconfig.json" specified in the "transform" object of Jest configuration
  must export a `process` or `processAsync` or `createTransformer` function.
  Code Transformation Documentation:
  https://jestjs.io/docs/code-transformation`
```

Let me know if find any solution to this.

3. These commands run smoothly though.
 
```
`npm run prepare`
`npm run lint`
`npm run build`
`npm start`
```
4. Updating with new changes with `git commit -m "message" --no-verify` commands, you will find what's inside in new and OLD files.

**Comment by lourot** [comment]
@sakibian Thank you for the detailed explanation! I'll have a look myself soon and get back to you. If I find an easy solution, do you mind if I push on top of your branch?

**Comment by sakibian** [comment]
@AurelienLourot It's fine you can.

**Review by lourot — CHANGES_REQUESTED** [review]
@sakibian I think everything will turn green now. Unfortunately it seems like the way we are building with parcel isn't equivalent with how it was built with tsdx (which uses rollup), as the example doesn't actually work. Build and run it locally with:

```
$ cd example/
$ ./clean-build-and-run.sh

Server running at http://localhost:1234
✨ Built in 2.58s
```

And then open http://localhost:1234 , you'll see failures. Thanks!

**Comment by sakibian** [comment]
@AurelienLourot I see the errors, I'm not an expert on JS or React, how do you suggest my contribution here?

**Comment by lourot** [comment]
I would use `rollup` the same way `tsdx` does by passing it a config file (e.g. `rollup.config.mjs`) similar to the rollup configuration generated by tsdx, which can be seen at https://github.com/jaredpalmer/tsdx/blob/master/src/createRollupConfig.ts

Let me give it a try :)

**Review by lourot — CHANGES_REQUESTED** [review]
@sakibian I got it working by switching to Rollup. However there is one remaining issue, which is when running `npm run build`, the resulting file `dist/react-image-display-control.esm.js` is now 10 times bigger than it used to be (432K instead of 36K).

This means I must have missed one of the rollup options used by tsdx (see https://github.com/jaredpalmer/tsdx/blob/master/src/createRollupConfig.ts) inside our rollup options `rollup.config.mjs`.

This might be the `treeshake` option, or maybe one of the `exclude:` or `external:` options.

Would you like to have a look? If not it's OK, I can dig a bit more. Thanks a lot!

**Review by lourot — APPROVED** [review]

**Comment by sakibian** [comment]
@AurelienLourot You got this sorted great, I wasn't working with the code because I thought I would break something. Well, I'm still learning and trying to get more grasp on code.

Let me know if I can contribute to any other project of yours. OR you could be my mentor guiding me to some other open-source paths.

**Comment by lourot** [comment]
Thanks for asking @sakibian. In the realm of [Frameright](https://github.com/frameright) we have quite a few other libraries and components you could contribute to. For example if you are into PHP, we have a [library](https://github.com/Frameright/php-image-metadata-parser) for parsing image metadata. https://github.com/Frameright/php-image-metadata-parser/issues/5 might be a good first issue.

**Pull request merged**
